language: go
go: 1.8.1
install:
  - make setup
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && gem install fpm && curl -sL https://git.io/goreleaser | bash
notifications:
  email: false
