#!/bin/bash
docker run \
  -v "$PWD":/go/src/github.com/caarlos0/cepinator \
  -w /go/src/github.com/caarlos0/cepinator \
  -e GOOS=linux \
  -e GOARCH=amd64 \
  -e CGO_ENABLED=0 \
  golang:1.8 \
  bash -c 'go build -tags netgo --ldflags "-extldflags "-static"" -o cepinator .'

docker build -t caarlos0/cepinator .
docker push caarlos0/cepinator
docker rmi caarlos0/cepinator
